/*
DM PACK
created with:
python /home/rdkb_test01/usr/include/rdkb/dm_pack_code_gen.py config/TestAndDiagnostic_arm.XML source/TandDSsp/dm_pack_datamodel.c
*/

#include "ansc_platform.h"
#include "ansc_xml_dom_parser_interface.h"
#include "dm_pack_xml_helper.h"
PVOID DMPackCreateDataModelXML(){
 PANSC_XML_DOM_NODE_OBJECT P0,P1,P2,P3,P4,P5,P6,P7,P8,P9;
 P0=DMPackCreatePNode(0,"dataModelInfo");
  P1=DMPackCreateNode(P0,"version","1",1);
  P1=DMPackCreateNode(P0,"moduleName","TestAndDiagnostic",17);
  P1=DMPackCreatePNode(P0,"author");
  P1=DMPackCreateNode(P0,"description","Test and Diagnostic",19);
  P1=DMPackCreatePNode(P0,"library");
   P2=DMPackCreateNode(P1,"path","libdmltad",9);
   P2=DMPackCreateNode(P1,"func_Init","COSA_Init",9);
   P2=DMPackCreateNode(P1,"func_Unload","COSA_Unload",11);
   P2=DMPackCreateNode(P1,"func_MemoryCheck","COSA_MemoryCheck",16);
   P2=DMPackCreateNode(P1,"func_MemoryUsage","COSA_MemoryUsage",16);
   P2=DMPackCreateNode(P1,"func_MemoryTable","COSA_MemoryTable",16);
  P1=DMPackCreatePNode(P0,"objects");
   P2=DMPackCreateObject(P1, 0,"Diagnostics",0);
    P3=DMPackCreateNode(P2,"baseObjName","Device.IP.",10);
    P3=DMPackCreatePNode(P2,"objects");
     P4=DMPackCreateObject(P3, 0,"X_CISCO_COM_ARP",0);
      DMPackCreateFunctions(P4,"X_CISCO_COM_ARP",4,10,11,12,13);
      P5=DMPackCreatePNode(P4,"parameters");
       DMPackCreateParamT(P5,"","");
      P5=DMPackCreatePNode(P4,"objects");
       P6=DMPackCreateObject(P5, 2,"ARPTable","128");
        DMPackCreateFunctions(P6,"ARPTable",8,0,2,5,6,10,11,12,13);
        P7=DMPackCreatePNode(P6,"parameters");
         DMPackCreateParamTS(P7,"IPAddress","string(40)","string");
         DMPackCreateParam(P7,"Static",0);
         DMPackCreateParamTS(P7,"MACAddress","string(18)","string");
     P4=DMPackCreateObject(P3, 0,"X_RDKCENTRAL-COM_PingTest",0);
      DMPackCreateFunctions(P4,"X_RDKCENTRAL_COM_PingTest",6,10,13,15,20,21,22);
      P5=DMPackCreatePNode(P4,"parameters");
       DMPackCreateW(P5,"Run",0,1);
       DMPackCreateParamTS(P5,"PartnerID","string(64)","string");
       DMPackCreateParamTS(P5,"ecmMAC","string(32)","string");
       DMPackCreateParam(P5,"DeviceID",3);
       DMPackCreateParam(P5,"DeviceModel",3);
     P4=DMPackCreateObject(P3, 0,"IPPing",0);
      DMPackCreateFunctions(P4,"IPPing",11,10,11,12,13,15,16,17,18,20,21,22);
      P5=DMPackCreatePNode(P4,"parameters");
       DMPackCreateParamTSWN(P5,"DiagnosticsState","string: None(1),Requested(2),Complete(3),Error_CannotResolveHostName(4),Error_Internal(5),Error_Other(6),Canceled(11)","uint32/mapped",1,0);
       DMPackCreateParamTSW(P5,"Interface","string(256)","string",1);
       DMPackCreateParamTSW(P5,"Host","string(256)","string",1);
       DMPackCreateParamTSW(P5,"NumberOfRepetitions","unsignedInt[1:]","uint32",1);
       DMPackCreateParamTSW(P5,"Timeout","unsignedInt[1:]","uint32",1);
       DMPackCreateParamTSW(P5,"DataBlockSize","unsignedInt[1:65535]","uint32",1);
       DMPackCreateParamTSW(P5,"DSCP","unsignedInt[0:63]","uint32",1);
       DMPackCreateN(P5,"SuccessCount",2,0);
       DMPackCreateN(P5,"FailureCount",2,0);
       DMPackCreateN(P5,"AverageResponseTime",2,0);
       DMPackCreateN(P5,"MinimumResponseTime",2,0);
       DMPackCreateN(P5,"MaximumResponseTime",2,0);
     P4=DMPackCreateObject(P3, 0,"TraceRoute",0);
      DMPackCreateFunctions(P4,"TraceRoute",11,10,11,12,13,15,16,17,18,20,21,22);
      P5=DMPackCreatePNode(P4,"parameters");
       DMPackCreateParamTSWN(P5,"DiagnosticsState","string: None(1),Requested(2),Complete(3),Error_CannotResolveHostName(4),Error_MaxHopCountExceeded(5),Canceled(6)","uint32/mapped",1,0);
       DMPackCreateParamTSW(P5,"Interface","string(256)","string",1);
       DMPackCreateParamTSW(P5,"Host","string(256)","string",1);
       DMPackCreateParamTSW(P5,"NumberOfTries","unsignedInt[1:3]","uint32",1);
       DMPackCreateParamTSW(P5,"Timeout","unsignedInt[1:]","uint32",1);
       DMPackCreateParamTSW(P5,"DataBlockSize","unsignedInt[1:65535]","uint32",1);
       DMPackCreateParamTSW(P5,"DSCP","unsignedInt[0:63]","uint32",1);
       DMPackCreateParamTSW(P5,"MaxHopCount","unsignedInt[1:64]","uint32",1);
       DMPackCreateN(P5,"ResponseTime",2,0);
       DMPackCreateN(P5,"RouteHopsNumberOfEntries",2,0);
      P5=DMPackCreatePNode(P4,"objects");
       P6=DMPackCreateObject(P5, 2,"RouteHops","128");
        DMPackCreateFunctions(P6,"RouteHops",8,0,2,5,6,10,11,12,13);
        P7=DMPackCreatePNode(P6,"parameters");
         DMPackCreateParamTSN(P7,"Host","string(256)","string",0);
         DMPackCreateN(P7,"HostAddress",3,0);
         DMPackCreateN(P7,"ErrorCode",2,0);
         DMPackCreateParamTSN(P7,"RTTimes","string(16)","string",0);
     P4=DMPackCreateObject(P3, 0,"DownloadDiagnostics",0);
      DMPackCreateFunctions(P4,"DownloadDiagnostics",11,10,11,12,13,15,16,17,18,20,21,22);
      P5=DMPackCreatePNode(P4,"parameters");
       DMPackCreateParamTSWN(P5,"DiagnosticsState","string: None(1),Requested(2),Completed(3),Error_InitConnectionFailed(4),Error_NoResponse(5),Error_TransferFailed(6),Error_PasswordRequestFailed(7),Error_LoginFailed(8),Error_NoTransferMode(9),Error_NoPASV(10),Error_IncorrectSize(11),Error_Timeout(12)","uint32/mapped",1,0);
       DMPackCreateParamTSW(P5,"Interface","string(256)","string",1);
       DMPackCreateParamTSW(P5,"DownloadURL","string(256)","string",1);
       DMPackCreateParam(P5,"DownloadTransports",3);
       DMPackCreateParamTSW(P5,"DSCP","unsignedInt[0:63]","uint32",1);
       DMPackCreateParamTSW(P5,"EthernetPriority","unsignedInt[0:7]","uint32",1);
       DMPackCreateParamTSN(P5,"ROMTime","dateTime","string",0);
       DMPackCreateParamTSN(P5,"BOMTime","dateTime","string",0);
       DMPackCreateParamTSN(P5,"EOMTime","dateTime","string",0);
       DMPackCreateN(P5,"TestBytesReceived",2,0);
       DMPackCreateN(P5,"TotalBytesReceived",2,0);
       DMPackCreateParamTSN(P5,"TCPOpenRequestTime","dateTime","string",0);
       DMPackCreateParamTSN(P5,"TCPOpenResponseTime","dateTime","string",0);
     P4=DMPackCreateObject(P3, 0,"UploadDiagnostics",0);
      DMPackCreateFunctions(P4,"UploadDiagnostics",11,10,11,12,13,15,16,17,18,20,21,22);
      P5=DMPackCreatePNode(P4,"parameters");
       DMPackCreateParamTSWN(P5,"DiagnosticsState","string: None(1),Requested(2),Completed(3),Error_InitConnectionFailed(4),Error_NoResponse(5),Error_PasswordRequestFailed(6),Error_LoginFailed(7),Error_NoTransferMode(8),Error_NoPASV(9),Error_NoCWD(10),Error_NoSTOR(11),Error_NoTransferComplete(12)","uint32/mapped",1,0);
       DMPackCreateParamTSW(P5,"Interface","string(256)","string",1);
       DMPackCreateParamTSW(P5,"UploadURL","string(256)","string",1);
       DMPackCreateParam(P5,"UploadTransports",3);
       DMPackCreateParamTSW(P5,"DSCP","unsignedInt[0:63]","uint32",1);
       DMPackCreateParamTSW(P5,"EthernetPriority","unsignedInt[0:7]","uint32",1);
       DMPackCreateW(P5,"TestFileLength",2,1);
       DMPackCreateParamTSN(P5,"ROMTime","dateTime","string",0);
       DMPackCreateParamTSN(P5,"BOMTime","dateTime","string",0);
       DMPackCreateParamTSN(P5,"EOMTime","dateTime","string",0);
       DMPackCreateN(P5,"TotalBytesSent",2,0);
       DMPackCreateParamTSN(P5,"TCPOpenRequestTime","dateTime","string",0);
       DMPackCreateParamTSN(P5,"TCPOpenResponseTime","dateTime","string",0);
     P4=DMPackCreateObject(P3, 0,"UDPEchoConfig",0);
      DMPackCreateFunctions(P4,"UDPEchoConfig",11,10,11,12,13,15,16,17,18,20,21,22);
      P5=DMPackCreatePNode(P4,"parameters");
       DMPackCreateW(P5,"Enable",0,1);
       DMPackCreateParamTSW(P5,"Interface","string(256)","string",1);
       DMPackCreateParamTSW(P5,"SourceIPAddress","string(256)","string",1);
       DMPackCreateW(P5,"UDPPort",2,1);
       DMPackCreateW(P5,"EchoPlusEnabled",0,1);
       DMPackCreateParam(P5,"EchoPlusSupported",0);
       DMPackCreateN(P5,"PacketsReceived",2,0);
       DMPackCreateN(P5,"PacketsResponded",2,0);
       DMPackCreateN(P5,"BytesReceived",2,0);
       DMPackCreateN(P5,"BytesResponded",2,0);
       DMPackCreateParamTSN(P5,"TimeFirstPacketReceived","dateTime","string",0);
       DMPackCreateParamTSN(P5,"TimeLastPacketReceived","dateTime","string",0);
     P4=DMPackCreateObject(P3, 0,"X_RDK_SpeedTest",0);
      DMPackCreateFunctions(P4,"RDK_SpeedTest",2,12,17);
      P5=DMPackCreatePNode(P4,"parameters");
       DMPackCreateW(P5,"SubscriberUnPauseTimeOut",2,1);
     P4=DMPackCreateObject(P3, 0,"X_RDKCENTRAL-COM_SpeedTest",0);
      DMPackCreateFunctions(P4,"SpeedTest",9,10,15,20,21,22,13,18,12,17);
      P5=DMPackCreatePNode(P4,"parameters");
       DMPackCreateW(P5,"Enable_Speedtest",0,1);
       DMPackCreateW(P5,"Run",0,1);
       DMPackCreateParamTSW(P5,"Argument","string(4096)","string",1);
       DMPackCreateW(P5,"ClientType",2,1);
       DMPackCreateParamTSW(P5,"Authentication","string(4096)","string",1);
       DMPackCreateParamTS(P5,"ClientVersion","string(32)","string");
       DMPackCreateW(P5,"Status",2,1);
      P5=DMPackCreatePNode(P4,"objects");
       P6=DMPackCreateObject(P5, 0,"Server",0);
        DMPackCreateFunctions(P6,"SpeedTestServer",3,10,13,18);
        P7=DMPackCreatePNode(P6,"parameters");
         DMPackCreateW(P7,"Capability",0,0);
         DMPackCreateParamTSW(P7,"Key","string(1024)","string",1);
         DMPackCreateParamTSW(P7,"Username","string(12)","string",1);
         DMPackCreateParamTSW(P7,"Password","string(12)","string",1);
     P4=DMPackCreateObject(P3, 0,"X_RDKCENTRAL-COM_RxTxStats",0);
      DMPackCreateFunctions(P4,"X_RDKCENTRAL_COM_RxTxStats",5,13,18,21,20,22);
      P5=DMPackCreatePNode(P4,"parameters");
       DMPackCreateParamTSW(P5,"InterfaceList","string(256)","string",1);
       DMPackCreateParamTSW(P5,"PortList","string(256)","string",1);
   P2=DMPackCreateObject(P1, 0,"DNS",0);
    P3=DMPackCreatePNode(P2,"objects");
     P4=DMPackCreateObject(P3, 0,"Diagnostics",0);
      P5=DMPackCreatePNode(P4,"objects");
       P6=DMPackCreateObject(P5, 0,"NSLookupDiagnostics",0);
        DMPackCreateFunctions(P6,"NSLookupDiagnostics",11,10,11,12,13,15,16,17,18,20,21,22);
        P7=DMPackCreatePNode(P6,"parameters");
         DMPackCreateParamTSWN(P7,"DiagnosticsState","string: None(1),Requested(2),Complete(3),Error_DNSServerNotResolved(4),Error_Internal(5),Error_Other(6)","uint32/mapped",1,0);
         DMPackCreateParamTSW(P7,"Interface","string(256)","string",1);
         DMPackCreateParamTSW(P7,"HostName","string(256)","string",1);
         DMPackCreateParamTSW(P7,"DNSServer","string(256)","string",1);
         DMPackCreateW(P7,"Timeout",2,1);
         DMPackCreateW(P7,"NumberOfRepetitions",2,1);
         DMPackCreateN(P7,"SuccessCount",2,0);
         DMPackCreateN(P7,"ResultNumberOfEntries",2,0);
        P7=DMPackCreatePNode(P6,"objects");
         P8=DMPackCreateObject(P7, 2,"Result","128");
          DMPackCreateFunctions(P8,"Result",8,0,2,5,6,10,11,12,13);
          P9=DMPackCreatePNode(P8,"parameters");
           DMPackCreateParamTSN(P9,"Status","string: Success(1),Error_DNSServerNotAvailable(2),Error_HostNameNotResolved(3),Error_Timeout(4),Error_Other(5)","uint32/mapped",0);
           DMPackCreateParamTSN(P9,"AnswerType","string: None(1),Authoritative(2),NonAuthoritative(3)","uint32/mapped",0);
           DMPackCreateParamTSN(P9,"HostNameReturned","string(256)","string",0);
           DMPackCreateParamTSN(P9,"IPAddresses","string(45)","string",0);
           DMPackCreateParamTSN(P9,"DNSServerIP","string(45)","string",0);
           DMPackCreateN(P9,"ResponseTime",2,0);
   P2=DMPackCreateObject(P1, 0,"SelfHeal",0);
    DMPackCreateFunctions(P2,"SelfHeal",9,10,15,12,17,13,18,20,21,22);
    P3=DMPackCreatePNode(P2,"parameters");
     DMPackCreateW(P3,"X_RDKCENTRAL-COM_FreeMemThreshold",2,1);
     DMPackCreateW(P3,"X_RDKCENTRAL-COM_MemFragThreshold",2,1);
     DMPackCreateParamTSW(P3,"X_RDKCENTRAL-COM_CpuMemFragInterval","unsignedInt[1:120]","uint32",1);
     DMPackCreateW(P3,"X_RDKCENTRAL-COM_Enable",0,1);
     DMPackCreateW(P3,"X_RDKCENTRAL-COM_MaxRebootCount",2,1);
     DMPackCreateW(P3,"X_RDKCENTRAL-COM_MaxResetCount",2,1);
     DMPackCreateW(P3,"X_RDKCENTRAL-COM_NoWaitLogSync",0,1);
     DMPackCreateW(P3,"X_RDKCENTRAL-COM_LogBackupThreshold",2,1);
     DMPackCreateW(P3,"X_RDKCENTRAL-COM_DiagnosticMode",0,1);
     DMPackCreateW(P3,"X_RDKCENTRAL-COM_DiagMode_LogUploadFrequency",2,1);
     DMPackCreateW(P3,"X_RDKCENTRAL-COM_DNS_PINGTEST_Enable",0,1);
     DMPackCreateParamTSW(P3,"X_RDKCENTRAL-COM_DNS_URL","string(512)","string",1);
    P3=DMPackCreatePNode(P2,"objects");
     P4=DMPackCreateObject(P3, 1,"CpuMemFrag","3");
      DMPackCreateFunctions(P4,"CpuMemFrag",4,0,2,13,12);
      P5=DMPackCreatePNode(P4,"parameters");
       DMPackCreateParamTSW(P5,"DMA","string(64)","string",0);
       DMPackCreateParamTSW(P5,"DMA32","string(64)","string",0);
       DMPackCreateParamTSW(P5,"Normal","string(64)","string",0);
       DMPackCreateParamTSW(P5,"Highmem","string(64)","string",0);
       DMPackCreateW(P5,"FragPercentage",2,0);
     P4=DMPackCreateObject(P3, 0,"ConnectivityTest",0);
      DMPackCreateFunctions(P4,"ConnectivityTest",6,10,15,12,17,11,16);
      P5=DMPackCreatePNode(P4,"parameters");
       DMPackCreateW(P5,"X_RDKCENTRAL-COM_PingInterval",2,1);
       DMPackCreateW(P5,"X_RDKCENTRAL-COM_NumPingsPerServer",2,1);
       DMPackCreateW(P5,"X_RDKCENTRAL-COM_MinNumPingServer",2,1);
       DMPackCreateW(P5,"X_RDKCENTRAL-COM_PingRespWaitTime",2,1);
       DMPackCreateW(P5,"X_RDKCENTRAL-COM_CorrectiveAction",0,1);
       DMPackCreateW(P5,"X_RDKCENTRAL-COM_LastReboot",2,1);
       DMPackCreateW(P5,"X_RDKCENTRAL-COM_RebootInterval",1,1);
       DMPackCreateW(P5,"X_RDKCENTRAL-COM_CurrentCount",1,1);
      P5=DMPackCreatePNode(P4,"objects");
       P6=DMPackCreateObject(P5, 0,"PingServerList",0);
        P7=DMPackCreatePNode(P6,"objects");
         P8=DMPackCreateObject(P7, 3,"IPv4PingServerTable","128");
          DMPackCreateFunctions(P8,"IPv4PingServerTable",11,0,2,5,6,3,4,13,18,20,21,22);
          P9=DMPackCreatePNode(P8,"parameters");
           DMPackCreateParamTSW(P9,"X_RDKCENTRAL-COM_Ipv4PingServerURI","string(256)","string",1);
         P8=DMPackCreateObject(P7, 3,"IPv6PingServerTable","128");
          DMPackCreateFunctions(P8,"IPv6PingServerTable",11,0,2,5,6,3,4,13,18,20,21,22);
          P9=DMPackCreatePNode(P8,"parameters");
           DMPackCreateParamTSW(P9,"X_RDKCENTRAL-COM_Ipv6PingServerURI","string(256)","string",1);
     P4=DMPackCreateObject(P3, 0,"ResourceMonitor",0);
      DMPackCreateFunctions(P4,"ResourceMonitor",5,12,17,20,21,22);
      P5=DMPackCreatePNode(P4,"parameters");
       DMPackCreateW(P5,"X_RDKCENTRAL-COM_UsageComputeWindow",2,1);
       DMPackCreateW(P5,"X_RDKCENTRAL-COM_AvgCPUThreshold",2,1);
       DMPackCreateW(P5,"X_RDKCENTRAL-COM_AvgMemoryThreshold",2,1);
     P4=DMPackCreateObject(P3, 0,"CPUProcAnalyzer",0);
      DMPackCreateFunctions(P4,"CPUProcAnalyzer",6,12,17,10,15,13,18);
      P5=DMPackCreatePNode(P4,"parameters");
       DMPackCreateW(P5,"Enable",0,1);
       DMPackCreateW(P5,"SleepInterval",2,1);
       DMPackCreateW(P5,"TimeToRun",2,1);
       DMPackCreateW(P5,"DynamicProcess",0,1);
       DMPackCreateW(P5,"MonitorAllProcess",0,1);
       DMPackCreateW(P5,"MemoryLimit",2,1);
       DMPackCreateW(P5,"ProcessList",3,1);
       DMPackCreateW(P5,"SystemStatsToMonitor",3,1);
       DMPackCreateW(P5,"ProcessStatsToMonitor",3,1);
       DMPackCreateW(P5,"TelemetryOnly",0,1);
   P2=DMPackCreateObject(P1, 0,"LogBackup",0);
    DMPackCreateFunctions(P2,"LogBackup",7,10,15,12,17,20,21,22);
    P3=DMPackCreatePNode(P2,"parameters");
     DMPackCreateW(P3,"X_RDKCENTRAL-COM_Enable",0,1);
     DMPackCreateW(P3,"X_RDKCENTRAL-COM_Interval",2,1);
     DMPackCreateW(P3,"X_RDKCENTRAL-COM_SyncandUploadLogs",0,1);
   P2=DMPackCreateObject(P1, 0,"PowerManagement",0);
    DMPackCreateFunctions(P2,"PowerManagement",5,10,15,20,21,22);
    P3=DMPackCreatePNode(P2,"parameters");
     DMPackCreateW(P3,"PciEPowerManagement",0,1);
   P2=DMPackCreateObject(P1, 0,"Thermal",0);
    P3=DMPackCreatePNode(P2,"objects");
     P4=DMPackCreateObject(P3, 1,"Fan","3");
      DMPackCreateFunctions(P4,"Fan",9,0,2,10,12,13,15,20,21,22);
      P5=DMPackCreatePNode(P4,"parameters");
       DMPackCreateParam(P5,"Status",0);
       DMPackCreateParam(P5,"Speed",2);
       DMPackCreateParamTS(P5,"RotorLock","string: Not_Applicable(1),True(2),False(3)","uint32/mapped");
       DMPackCreateW(P5,"MaxOverride",0,1);
   P2=DMPackCreateObject(P1, 0,"X_RDK_hwHealthTest",0);
    DMPackCreateFunctions(P2,"hwHealthTest",3,10,15,13);
    P3=DMPackCreatePNode(P2,"parameters");
     DMPackCreateW(P3,"executeTest",0,1);
     DMPackCreateParamTS(P3,"Results","string(512)","string");
   P2=DMPackCreateObject(P1, 0,"X_RDK_AutomationTest",0);
    DMPackCreateFunctions(P2,"X_RDK_AutomationTest",2,13,18);
    P3=DMPackCreatePNode(P2,"parameters");
     DMPackCreateParamTSW(P3,"Run","string(180)","string",1);
     DMPackCreateParamTS(P3,"Status","string(32)","string");
     DMPackCreateParamTS(P3,"Result","string(512)","string");
 return P0;
}
